# Generated by Django 4.2.29 on 2026-03-08 01:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("content", tinymce.models.HTMLField()),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Paste a Google Drive share link or any direct image URL.",
                        max_length=500,
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="Paste a Google Drive share link or any direct audio URL.",
                        max_length=500,
                    ),
                ),
                (
                    "random_likes",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Auto-generated random number (100–1000) on creation.",
                    ),
                ),
                (
                    "real_likes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Incremented every time a user clicks the like button.",
                    ),
                ),
                ("publish_date", models.DateTimeField()),
                ("edit_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-publish_date"],
            },
        ),
    ]
